### ISSUE TITLE
Full path to csproj file yeilds error message "Specified file is not .csproj file."

### ISSUE THREAD

**Issue by haggerty-william** [Hubert-Rybak/DotnetPack#15]
example command line input and output is below. The path to the csproj file is correct and the build command 'dotnet build ClipExport/ClipExport.csproj' works without issue. I know the correct way to use this is to not specify the exact location but to specify the directory it is in, but I am very used to specifying full paths and the error message is just wrong.

whaggerty@ubuntu:~/Github/PlatformServices$ dotnet-warp ClipExport/ClipExport.csproj
Specified file is not .csproj file.
Specify --help for a list of available options and commands.

**Comment by Hubert-Rybak** [comment]
Fixed in 1.0.5
