### ISSUE TITLE
Consider renaming this tool

### ISSUE THREAD

**Issue by TheBlueSky** [Hubert-Rybak/DotnetPack#2]
First of all, thanks for this useful tool; it maks using Warp simpler.

This tool, on the other hand, is unfortunately named `dotnet-pack` which conflicts with the build-in command `dotnet pack`.

**Comment by Hubert-Rybak** [comment]
Agree, realized it recently that this name could be somewhat unfortunate. Maybe dotnet-warp ?

**Comment by TheBlueSky** [comment]
Yeah, `dotnet-warp` would make more sense.
