### ISSUE TITLE
Resulting EXE Has no version information and no resource file to be edited

### ISSUE THREAD

**Issue by jpatersonlpa** [Hubert-Rybak/DotnetPack#20]
Can we have the resulting EXE take on the file version, description etc from the core assembly?  I personally use this for seeing if an application requires an update and I'm sure it would come in handy for other users.

**Comment by Hubert-Rybak** [comment]
I investigated it, and it seems that would be non trivial to do plainly in C#. 
This library relies on Warp for exe packaging, so maybe try filling an issue there?

**Comment by Hubert-Rybak** [comment]
Related: https://github.com/dgiagio/warp/issues/32
