### ISSUE TITLE
Does pack command incorrectly determine the exe name?

### ISSUE THREAD

**Issue by larstbone** [Hubert-Rybak/DotnetPack#23]
For a console app named like "AcmeImport.Console" the default assembly name will be "AcmeImport.Console"  However, the pack command below looks for "AcmeImport.exe" in the publish directory.  Note the missing ".Console". 

`[...]windows-x64.warp-packer.exe --arch windows-x64 --input_dir "C:\all\AcmeImport\AcmeImport.Console\dotnetwarp_temp" --exec "AcmeImport.exe" --output "AcmeImport.exe"`

My work around was to edit project properties renaming the assembly to "AcmeImport" which results in an exe that the pack command will hit.

**Comment by Hubert-Rybak** [comment]
Fixed in #24
