### ISSUE TITLE
Allow to specify additional Parameters (i.e. Version) to be used with dotnet publish command.

### ISSUE THREAD

**Issue by vipetrul** [Hubert-Rybak/DotnetPack#25]
It would be very useful if one could pass parameters (i.e. `/p:Version=1.2.3`) to be used with `dotnet publish` command.
I could create a pull request if this functionality is desired and we can agree on a method how to specify those parameters.
Thanks!

**Comment by Hubert-Rybak** [comment]
Hi,
I think it's a good idea, however some of this parameters (i.e. Version) will not affect output executable, because final packing is done in Warp. 
There is an existing issue in Warp to add possibility to pass additional information about resulting exe (https://github.com/dgiagio/warp/issues/32).

**Comment by vipetrul** [comment]
You right, it will not affect output executable. But I do have a use-case where main application needs to evaluate it's version before performing a task. I believe native application version would be still available, once it is unpacked by output executable.

I understand if "Version" feature is not yet desirable in dotnet-wrap. If this is the case, I then would use wrap directly to pack an executable.

Thank you for consideration.

**Comment by Hubert-Rybak** [comment]
You misunderstood me :) I think it is desirable, but Version attribute will not work and I thought that this is your use-case.
I think that best approach here is to add option which will pass "raw" arguments to dotnet publish to handle all possible cases and scenarios and not constrain dotnet publish in any way. What do you think?

**Comment by vipetrul** [comment]
I agree that adding generic Arguments option would be the most flexible solution. I will submit a pull request.

**Comment by vipetrul** [comment]
#26

**Comment by vipetrul** [comment]
Bump. Just wanted to see if you had a chance to look at pull request.
Thank you.
