### ISSUE TITLE
Folder with multiple .csproj files

### ISSUE THREAD

**Issue by ztl8702** [Hubert-Rybak/DotnetPack#27]
Is this a supported scenario? 

I can see the following line in code:

https://github.com/Hubert-Rybak/dotnet-warp/blob/3a8a590be9fc944dddea8038b8dfdd8aab476a9b/src/dotnet-warp/Program.cs#L79

But it seems I can't pass in a `--project` parameter:

```
> dotnet-warp --project .\Foo.csproj --verbose
Specify --help for a list of available options and commands.
Unrecognized option '--project'

Did you mean this?
    property
```

**Comment by Hubert-Rybak** [comment]
Project is first parameter, try
dotnet-warp .\Foo.csproj
