### ISSUE TITLE
Allow option to specify RID for dotnet publish

### ISSUE THREAD

**Issue by Hubert-Rybak** [Hubert-Rybak/DotnetPack#3]
Currently, RID is selected automatically from these: "win-x64", "linux-x64", "osx-x64", but they may might not be always correct for given scenario. 
Because of that its not possible, for example, to produce binary for Linux while being on Windows.

**Comment by queensengineer** [comment]
RID seems to select both the runtime and the binary used, so it seems impossible to select Windows target while compiling on linux (docker-in-docker)
