### ISSUE TITLE
Zsh is not supported

### ISSUE THREAD

**Issue by MartinLau7** [Hubert-Rybak/DotnetPack#32]
I installed dotnet-warp in macOS, but it seems that dotnet-warp currently only supports execution in bash, and can no longer be executed in zsh.

**Comment by Hubert-Rybak** [comment]
Hmm, strange... Have you tried running Warp (https://github.com/dgiagio/warp) directly?
Also, what specific error do you have on zsh?

**Comment by MartinLau7** [comment]
It seems to be a dotnet environment issue, I have reinstalled and fixed it.
