### ISSUE TITLE
Update nuget version to support cross compilation

### ISSUE THREAD

**Issue by chphilli** [Hubert-Rybak/DotnetPack#36]
I'm running into an issue where trying to cross compile ( linux container creating windows .exe ) is failing because dotnet-warp tries to execute the warp executable using the target version rather than an executable appropriate for the host system. This appears to have been fixed in a16356 a month ago but the latest version of dotnet-warp on nuget is 1.0.9 from 3 months ago. 

Any chance you could push a new version to nuget to support this use case?

**Comment by cobbr** [comment]
Running into the same issue 👍

**Comment by Hubert-Rybak** [comment]
Sorry for the delay. Pushed new version to nuget.
