### ISSUE TITLE
Add support for vbproj

### ISSUE THREAD

**Issue by elachlan** [Hubert-Rybak/DotnetPack#37]
Visual Basic is now supported in .Net Core 3. The tool should probably support it.

**Comment by Hubert-Rybak** [comment]
It should be easy, just need to add vbroj here:
https://github.com/Hubert-Rybak/dotnet-warp/blob/af7e332c11f46bf68f98d0467f26709473779817/src/dotnet-warp/Program.cs#L56
Mind adding a PR?
