### ISSUE TITLE
dotnet-warp does not work on a mac

### ISSUE THREAD

**Issue by EifelMono** [Hubert-Rybak/DotnetPack#8]
The warp-packer is called with osx-x64
macos-x64.warp-packer **--arch osx-x64** .......

but must be called with macos-x64
macos-x64.warp-packer --arch **macos-x64** ......

**Comment by EifelMono** [comment]
MacBook003:warp1 andreas$ dotnet publish -c Release -r osx-x64 -o dotnetwarp_temp /p:ShowLinkerSizeComparison=true /Users/andreas/dev/bugs/warp1  
Microsoft (R)-Build-Engine, Version 16.0.385-preview+g966cdf2ac6 für .NET Core
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  Wiederherstellung in "30,37 ms" für "/Users/andreas/dev/bugs/warp1/warp1.csproj" abgeschlossen.
/usr/local/share/dotnet/sdk/3.0.100-preview-010184/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: Sie verwenden eine Vorschauversion von .NET Core. Weitere Informationen: https://aka.ms/dotnet-core-preview [/Users/andreas/dev/bugs/warp1/warp1.csproj]
  warp1 -> /Users/andreas/dev/bugs/warp1/bin/Release/netcoreapp3.0/osx-x64/warp1.dll
  warp1 -> /Users/andreas/dev/bugs/warp1/dotnetwarp_temp/
MacBook003:warp1 andreas$ /Users/andreas/.dotnet/tools/.store/dotnet-warp/1.0.3/dotnet-warp/1.0.3/tools/netcoreapp2.2/any/warp/macos-x64.warp-packer --arch osx-x64 --input_dir /Users/andreas/dev/bugs/warp1/dotnetwarp_temp --exec warp1 --output warp1
Unknown architecture specified: osx-x64, supported: ["macos-x64", "linux-x64", "windows-x64"]
MacBook003:warp1 andreas$ /Users/andreas/.dotnet/tools/.store/dotnet-warp/1.0.3/dotnet-warp/1.0.3/tools/netcoreapp2.2/any/warp/macos-x64.warp-packer --arch macos-x64 --input_dir /Users/andreas/dev/bugs/warp1/dotnetwarp_temp --exec warp1 --output warp1
Compressing input directory "/Users/andreas/dev/bugs/warp1/dotnetwarp_temp"...
Creating self-contained application binary "warp1"...
All done
MacBook003:warp1 andreas$ ./warp1 
Hello World!
MacBook003:warp1 andreas$

**Comment by Hubert-Rybak** [comment]
Would you like to contribute? I could change it, but I dont have access to Mac to test it

**Comment by EifelMono** [comment]
yes
